name: Frontend part of Zerro-app
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Navigate to client directory
        run: cd client
      - name: install modules
        run: npm install
        working-directory: client

      - name: build project
        run: npm run build
        working-directory: client

#      - name: ES lint
#        run: npm run lint
#        working-directory: client

      - name: build sb
        run: npm run build-storybook
        working-directory: client

      - name: unit tests
        run: npm run test
        working-directory: client

