name: Frontend part of Zerro-app
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Clean cache and modules
        run: |
          cd client
          rm -rf node_modules package-lock.json
          npm cache clean --force
        working-directory: ./

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (no optional)
        run: npm install --no-optional
        working-directory: client

      - name: Build project
        run: npm run build --verbose
        working-directory: client

      - name: ESLint
        run: npm run lint
        working-directory: client

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: client

      - name: Unit tests
        run: npm run test
        working-directory: client